-- MySQL Script generated by MySQL Workbench
-- Tue Nov  3 12:18:05 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema advertisy
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema advertisy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `advertisy` DEFAULT CHARACTER SET utf8 ;
USE `advertisy` ;

-- -----------------------------------------------------
-- Table `advertisy`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `advertisy`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `advertisy`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `advertisy`.`city` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `acronim` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `advertisy`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `advertisy`.`country` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `acronim` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `advertisy`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `advertisy`.`address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(45) NULL,
  `city_id` INT NULL,
  `contry_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_address_city_idx` (`city_id` ASC),
  INDEX `fk_address_country1_idx` (`contry_id` ASC),
  CONSTRAINT `fk_address_city`
    FOREIGN KEY (`city_id`)
    REFERENCES `advertisy`.`city` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_address_country1`
    FOREIGN KEY (`contry_id`)
    REFERENCES `advertisy`.`country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `advertisy`.`account_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `advertisy`.`account_type` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `advertisy`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `advertisy`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(255) NULL,
  `role_id` INT NULL,
  `account_type_id` INT NULL,
  `file_id` INT NULL,
  `f_name` VARCHAR(45) NULL,
  `l_name` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `active` TINYINT NULL DEFAULT 1,
  `last_login` TIMESTAMP NULL,
  `address_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_user_role1_idx` (`role_id` ASC),
  INDEX `fk_user_address1_idx` (`address_id` ASC),
  INDEX `fk_user_account_type1_idx` (`account_type_id` ASC),
  CONSTRAINT `fk_user_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `advertisy`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `advertisy`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_account_type1`
    FOREIGN KEY (`account_type_id`)
    REFERENCES `advertisy`.`account_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `advertisy`.`file`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `advertisy`.`file` (
  `id` INT NOT NULL,
  `uuid` VARCHAR(45) NULL,
  `sha` VARCHAR(45) NULL,
  `name` VARCHAR(255) NULL,
  `blob` BLOB NULL,
  `mime_type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `advertisy`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `advertisy`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(2550) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `advertisy`.`announce`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `advertisy`.`announce` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category_id` INT NULL,
  `title` VARCHAR(45) NULL,
  `short_desc` VARCHAR(2550) NULL,
  `long_desc` LONGTEXT NULL,
  `price` DOUBLE NULL,
  `views` INT NULL,
  `is_active` TINYINT NULL,
  `is_publiced` TINYINT NULL,
  `publice_date` DATE NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_announce_category1_idx` (`category_id` ASC),
  CONSTRAINT `fk_announce_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `advertisy`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `advertisy`.`announce_file`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `advertisy`.`announce_file` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `file_id` INT NULL,
  `announce_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_announce_file_announce1_idx` (`announce_id` ASC),
  INDEX `fk_announce_file_file1_idx` (`file_id` ASC),
  CONSTRAINT `fk_announce_file_announce1`
    FOREIGN KEY (`announce_id`)
    REFERENCES `advertisy`.`announce` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_announce_file_file1`
    FOREIGN KEY (`file_id`)
    REFERENCES `advertisy`.`file` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `advertisy`.`announce_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `advertisy`.`announce_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL,
  `announce_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_announce_user_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_announce_user_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `advertisy`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_announce_user_announce1`
    FOREIGN KEY (`id`)
    REFERENCES `advertisy`.`announce` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `advertisy`.`reported_announce`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `advertisy`.`reported_announce` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `announce_id` INT NULL,
  `message` VARCHAR(2550) NULL,
  `report_date` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_reported_announce_announce1_idx` (`announce_id` ASC),
  CONSTRAINT `fk_reported_announce_announce1`
    FOREIGN KEY (`announce_id`)
    REFERENCES `advertisy`.`announce` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `advertisy`.`banned_announce`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `advertisy`.`banned_announce` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `announce_id` INT NULL,
  `message` VARCHAR(2550) NULL,
  `ban_date` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_banned_announce_announce1_idx` (`announce_id` ASC),
  CONSTRAINT `fk_banned_announce_announce1`
    FOREIGN KEY (`announce_id`)
    REFERENCES `advertisy`.`announce` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `advertisy`.`unban_announce_req`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `advertisy`.`unban_announce_req` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `announce_id` INT NULL,
  `message` VARCHAR(2550) NULL,
  `req_date` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_unban_announce_req_announce1_idx` (`announce_id` ASC),
  CONSTRAINT `fk_unban_announce_req_announce1`
    FOREIGN KEY (`announce_id`)
    REFERENCES `advertisy`.`announce` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
